### ISSUE TITLE
Future suggestions

### ISSUE THREAD

**Issue by LSSwwwwwww** [andersspielen/PotionGamesIssues#5]
How about add a team mode?You can create the team mode when you setup the map.And add the games leave item?Because it seems that everyone must use the command to leave the games rather than use item.

**Comment by LSSwwwwwww** [comment]
Or how about add /pg join <arena name> rather than /pg join to choose the arena.

**Comment by andersspielen** [comment]
What exactly do you mean with team mode and with your /pg join command?

**Comment by LSSwwwwwww** [comment]
team mode is that when you create an arena and make the team mode.Player can choose red yellow blue green or other style when they join the games.Just like Bedwars.  /pg join <arena name> is that.when you finish create the map.And you doesn't use the oak_sign.You must use /pg join to join the lobby and use paper to choose map.If you can add /pg join <arena name> it will be great for the menu plugin.

**Comment by LSSwwwwwww** [comment]
team mode is that when you create an arena and make the team mode.Player can choose red yellow blue green or other style when they join the games.Just like Bedwars.  /pg join <arena name> is that.when you finish create the map.And you doesn't use the oak_sign.You must use /pg join to join the lobby and use paper to choose map.If you can add /pg join <arena name> it will be great for the menu plugin.

**Comment by andersspielen** [comment]
Have you tried /pg list? It shows all your lobbies with all additional information.

**Comment by LSSwwwwwww** [comment]
[21:52:09 WARN]: [PotionGames] Task #423 for PotionGames v4.7 generated an exception
>java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
at com.asga.potiongames.main.PotionGames.lambda$tick$1(PotionGames.java:1893) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
at java.lang.Thread.run(Thread.java:831) [?:?]
[21:52:10 WARN]: [PotionGames] Task #423 for PotionGames v4.7 generated an exception
>java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
at com.asga.potiongames.main.PotionGames.lambda$tick$1(PotionGames.java:1893) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
at java.lang.Thread.run(Thread.java:831) [?:?]
[21:52:11 WARN]: [PotionGames] Task #423 for PotionGames v4.7 generated an exception
>java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
at com.asga.potiongames.main.PotionGames.lambda$tick$1(PotionGames.java:1893) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
at java.lang.Thread.run(Thread.java:831) [?:?]
emmmm I use pg list It can't work.......And I don't know why it have this error just now.

**Comment by andersspielen** [comment]
Wait I have a look at it.

**Comment by andersspielen** [comment]
Do you use the LobbySystem (so that you can have multiple lobbies) or only one lobby? When you only use one lobby /pg list don't work.

**Comment by LSSwwwwwww** [comment]
only one lobby.I restart the server and it doesn;t have this error now.

**Comment by andersspielen** [comment]
the error is because the plugin could not found any arena and so the vote result was null (empty)

**Comment by andersspielen** [comment]
I am trying to replecate the error but I think it was a fault on your site not on the plugin one's.

**Comment by LSSwwwwwww** [comment]
Oh yes.I just finish create the arena.and first join the arena it has the map.But when I use pg leave.The error occur and It doesn't have any maps.  I have a question when I use /pg setup and my servser's someone say he also have the setup tools......

**Comment by andersspielen** [comment]
Yes I found the mistake when he is chatting, while you are in setup mode he performes a PlayerChatEvent and also gets the setup items in his inventory! - I will fix this today or tomorrow.

**Comment by andersspielen** [comment]
Back to your suggestions, with team mode you mean that you can see your mates better and can't damage them and so on?

**Comment by LSSwwwwwww** [comment]
yes

**Comment by andersspielen** [comment]
Ok, that I also want to add and I think I also will come in the Version 5.0

And the /pg list gui:
![2021-07-11_16 11 54](https://user-images.githubusercontent.com/58660689/125198981-80c60480-e264-11eb-8c55-a5a7efda1bed.png)

**Comment by andersspielen** [comment]
Do you mean something like with your command at the beginnig?

**Comment by LSSwwwwwww** [comment]
emmm which command.....

**Comment by andersspielen** [comment]
You wrote: You must use /pg join to join the lobby and use paper to choose map.If you can add /pg join it will be great for the menu plugin.

**Comment by LSSwwwwwww** [comment]
emmmm /pg join mapname    to direct to join the arena

**Comment by andersspielen** [comment]
ahhhhh, now i understand that is not possible with the system i created, but maybe i can make it so that when you only added on map that it is automaticly choosen and the Arena-Selector item is removed from your inventroy!
To give you some background information:
All theses steps like lobby, teleporting to the arena and back into the lobby are the ground of my plugin , so when I want to remove the lobby and make the arena the new lobby i have to rewrite the whole plugin.

**Comment by LSSwwwwwww** [comment]
So when will you finish your version 5.0

**Comment by andersspielen** [comment]
When I want to include all your ideas, than it will take a while. So I would say maybe end of this or next month! But I can not guarantee you that I am able to implement thing like the airdrop, but I will try it!

**Comment by LSSwwwwwww** [comment]
And add the magma_cream bind /pg leave  will be great.

**Comment by andersspielen** [comment]
The things I changed today were relativ simple or already implemented by me, so I only needed to copy or delete a line. The other tings are more complicated and they need their time. yeah the /pg leave item will be added before the Version 5.0 maybe I make a Update for tomorrow, where I fix the /pg setup bug change the explode time and damage of the tnt and add the /pg leave item:

**Comment by andersspielen** [comment]
Do you want lower explode time and higher damage or something else?

**Comment by LSSwwwwwww** [comment]
both need will be more great.Because TNT might be the best gun to kill the diamond eqid.

**Comment by LSSwwwwwww** [comment]
equip

**Comment by andersspielen** [comment]
ok

**Comment by LSSwwwwwww** [comment]
How about give TNT a new name:&dDetonator  Lore:"A powerful TNT" "Make sure you're away from it"

**Comment by andersspielen** [comment]
Yeah the I can do easily also doing it tomorrow

**Comment by andersspielen** [comment]
> The things I changed today were relativ simple or already implemented by me, so I only needed to copy or delete a line. The other tings are more complicated and they need their time. yeah the /pg leave item will be added before the Version 5.0 maybe I make a Update for tomorrow, where I fix the /pg setup bug change the explode time and damage of the tnt and add the /pg leave item:

Update ready will be released later!

**Comment by LSSwwwwwww** [comment]
At the beginning of the game, it seems that the protection time of about 10 seconds is gone. Secondly, can we make a true/off in the config.yml about world-chatting to block the outside chat, because there is no need to turn off the chat with the outside world in the hunger game

**Comment by LSSwwwwwww** [comment]
I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.

**Comment by andersspielen** [comment]
> At the beginning of the game, it seems that the protection time of about 10 seconds is gone. Secondly, can we make a true/off in the config.yml about world-chatting to block the outside chat, because there is no need to turn off the chat with the outside world in the hunger game

I can make a potion, but for bigger servers that have multiple lobbies on one server it is better to only see the in-game chat

**Comment by andersspielen** [comment]
> I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.

Do you have the lobby or the arenas in the same world as you have other things? Then it is right that pvp is turned off. If not I can have a look at it.

**Comment by LSSwwwwwww** [comment]
> > I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.
> 
> Do you have the lobby or the arenas in the same world as you have other things? Then it is right that pvp is turned off. If not I can have a look at it.

How can I close the auto PVP turn off?

**Comment by andersspielen** [comment]
> > > I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.
> > 
> > Do you have the lobby or the arenas in the same world as you have other things? Then it is right that pvp is turned off. If not I can have a look at it.
> 
> How can I close the auto PVP turn off?

You can't turn it off, because it's a feature, so that you cant punch anyone in the lobby or in the arena before it started

**Comment by LSSwwwwwww** [comment]
> > > > I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.
> > > 
> > > 
> > > Do you have the lobby or the arenas in the same world as you have other things? Then it is right that pvp is turned off. If not I can have a look at it.
> > 
> > 
> > How can I close the auto PVP turn off?
> 
> You can't turn it off, because it's a feature, so that you cant punch anyone in the lobby or in the arena before it started

So make the lobby in a lonely world the problem will be solve?

**Comment by andersspielen** [comment]
> > > > > I don't know if it's your plug-in. Every time I restart the server, the PVP of the multiverse core plug-in will be turned off.
> > > > 
> > > > 
> > > > Do you have the lobby or the arenas in the same world as you have other things? Then it is right that pvp is turned off. If not I can have a look at it.
> > > 
> > > 
> > > How can I close the auto PVP turn off?
> > 
> > You can't turn it off, because it's a feature, so that you cant punch anyone in the lobby or in the arena before it started
> 
> So make the lobby in a lonely world the problem will be solve?

Yes exactly, should solve your problem. I tested this a long time ago and never changed anything at that system.

**Comment by LSSwwwwwww** [comment]
ok,so what's your plan in the next version? 4.7.2?

**Comment by andersspielen** [comment]
> ok,so what's your plan in the next version? 4.7.2?

The thing you requested to turn off the blocking of the chat to the outside chat.
The other things are all for Version 5.0 as you can see on the issues front page.

**Comment by andersspielen** [comment]
4.7.2 should be ready in the next hours

**Comment by LSSwwwwwww** [comment]
ok so are you going to add the deathmatch in your next version?    Maybe when the time left 1 min the player will teleport to a place.where the size is 30x30

**Comment by andersspielen** [comment]
> ok so are you going to add the deathmatch in your next version?    Maybe when the time left 1 min the player will teleport to a place.where the size is 30x30

No I don't think so I want to make a world border that ends in a size like 30x30 and so they can fight in the normal arena, but I can have a look at it and maybe add it also.

**Comment by LSSwwwwwww** [comment]
emmmm.If use world border maybe it will have performance problem......

**Comment by LSSwwwwwww** [comment]
And maybe one games need one world......

**Comment by andersspielen** [comment]
Yeah you are right have not think at this, then I will make a deathmatch arena

**Comment by andersspielen** [comment]
Version 4.7.2 is online btw

**Comment by andersspielen** [comment]
Maybe you can test the chat feature because I have no time for it now.

**Comment by LSSwwwwwww** [comment]
ok:-)



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 12, 2021 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [andersspielen/PotionGamesIssues] Future suggestions (#5)




 
Maybe you can test the chat feature because I have no time for it now.

**Comment by LSSwwwwwww** [comment]
How about close the updatechecking?

**Comment by LSSwwwwwww** [comment]
So why it doesn't have message when the protect time end.  0.0

**Comment by andersspielen** [comment]
> How about close the updatechecking?

What do you mean with that?

**Comment by LSSwwwwwww** [comment]
is the plugin update checking....

**Comment by andersspielen** [comment]
No only when you start the server or join the server with the right permissions or you use the command

**Comment by LSSwwwwwww** [comment]
Yes is when start the server.How can I close it?  Because another server doesn't support connect other country website and it will make the start very slow......

**Comment by andersspielen** [comment]
I will add an option to the config, have not thought at something like that. Or I add a time limit.

**Comment by andersspielen** [comment]
[PotionGames-4.7.2.1.zip](https://github.com/andersspielen/PotionGamesIssues/files/6801212/PotionGames-4.7.2.1.zip)
Can you test this? - Should fix the update checking issue!

**Comment by andersspielen** [comment]
And does the error also occure when you join the server as a player?

**Comment by LSSwwwwwww** [comment]
OK but before that how can I solve the problem.In a 15 people server test.When player die and it will also bring back to life in the world spawnpoint how can I solve it?

**Comment by andersspielen** [comment]
I dont understand you problem? Can you discribe it a little bit clearer

**Comment by LSSwwwwwww** [comment]
Can I reprint your plugin in the MCBBS? It is the Chinese biggest MC website.I will reprint it in your name

**Comment by andersspielen** [comment]
> Can I reprint your plugin in the MCBBS? It is the Chinese biggest MC website.I will reprint it in your name

Yes you can

**Comment by LSSwwwwwww** [comment]
That is, when the player in the game dies, the player will resurrect in the game field. I don't know how to describe this bug. Besides, I took a video, but I don't know how to send it to you

**Comment by andersspielen** [comment]
you can copy the video in the text box

**Comment by andersspielen** [comment]
Normally the player who died should be in spactator mode untill the round ends

**Comment by LSSwwwwwww** [comment]
This video is too big.Giving me some times to solve it.

**Comment by andersspielen** [comment]
you can put it in a zip container, this should make i smaler, or upload it to mediafire or some other file sharing platforms

**Comment by LSSwwwwwww** [comment]
emmmm but it only support the video not more that 10MB

**Comment by andersspielen** [comment]
the you need to upload it to some other platform

**Comment by LSSwwwwwww** [comment]
How about the discord?Do you have the discord?

**Comment by andersspielen** [comment]
c4tch21#9628

**Comment by LSSwwwwwww** [comment]
emmmm.....this is the piece of the video Do you find the problem?

https://user-images.githubusercontent.com/76869684/125289179-86e5df00-e351-11eb-9d08-a76a404bb624.mov

**Comment by andersspielen** [comment]
yes i see, i have to test it my self later with a friend of mine
